config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'

 
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',          via: 'get'
  match '/signout', to: 'sessions#destroy',      via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/video', to: 'static_pages#video', via: 'get'
  match '/tutorial', to: 'static_pages#tutorial', via: 'get'
  match '/graph', to: 'static_pages#graph', via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	  before_save { self.email = email.downcase }
  	  before_create :create_remember_token
	#attr_accessor :name, :email, :password, :password_confirmation
	
	has_secure_password

	
	before_save { self.email = email.downcase }
	validates :name, presence:true, length:{maximum:50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
  						uniqueness: { case_sensitive: false }
  	validates :password, length:{minimum:6}
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
   		user = User.find_by(email: params[:session][:email].downcase)
   		if user && user.authenticate(params[:session][:password])
     			 sign_in user
     			 redirect_to user
 		else
     		flash.now[:error] = 'Invalid email/password combination' # Not quite right!
     		render 'new'
   		end
 	end

	def destroy
    sign_out
    redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def help
  end
  def about
  end
  def video
  end
  def tutorial
  end
  def graph
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
       flash[:success] = "Profile updated"
       redirect_to @user
    else
      render 'edit'
    end
  end
  
  def show
  		@user = User.find(params[:id])
  end
	def new
  		@user = User.new
  end

  def create
  		 @user = User.new(user_params)
  		if @user.save
  			  flash[:success] = "Welcome to the CoinStats App! Now please signin to the application "
  			redirect_to @user
  		# Handle a successful save
  		else
  			render 'new'
  		end
  end

 	private
  def user_params
      	params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "CoinStats"
		if page_title.empty?
			base_title
		else 
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
 	def sign_in(user)
    	remember_token = User.new_remember_token
    	cookies.permanent[:remember_token] = remember_token
    	user.update_attribute(:remember_token, User.encrypt(remember_token))
    	self.current_user = user
	end
 	def signed_in?
    	!current_user.nil?
    end
    def current_user=(user)
    @current_user = user
 	end
    def current_user
    	remember_token = User.encrypt(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token)
    end
    def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://bitcoin.org/en/">BitStats</a>
    by Darren Doyle
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><a href="https://bitcoin.org/en/">Newss</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "CoinStats", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profiles", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Tutorial", tutorial_path %></li>
                 <li><%= link_to "Videos", video_path %></li>
                   <li><%= link_to "Graph", graph_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class ="container">
     <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<%provide(:title, 'About Us')%>
    <h1>About Us</h1>
    <p>
      The <a href="https://bitcoin.org/en/">Bitcoin information page</a>
      is a project about Bitcoins
      with. This
      is the application for my Cloud Development Project
    </p>
  

app/views/static_pages/graph.html.erb
<aside class="span4">
    <section>
     <h1>Real-Time graphs</h1>
    </section>
  </aside>
      <p><iframe height="820" width="100%" src="https://www.statsmix.com/d/16e3031a50573d8bdc31" frameborder="0" scrolling="no"></iframe></p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>
    <h1>Help</h1>
    <p>To find out more information please contact <a href="mailto:darsedoyle@gmail.com?subject=Help Bitcoin">
Darren </a> at my email </p> 
   
  

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to CoinStats</h1>

  <h2>
    Information on BitCoin
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<<div class="container marketing">
      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="span4">
          <img class="img-circle" data-src="holder.js/140x140" alt="140x140" style="width: 140px; height: 140px;" <%= image_tag "ico_network.svg" %>
          <h2>Participate</h2>
          <p>Bitcoin is a protocol that was born from a small community and has grown fast since. There are a lot of things you can do to help Bitcoin to spread and improve over time.Checkout out the tutorial page when you sign up</p>
        	 <% if signed_in? %>
        	 <%= link_to "View details", tutorial_path, :class => "btn" %>
       			<% else %>
        		 <%= link_to "View details", signin_path, :class => "btn" %>
        	 <% end %>
        </div>
        <div class="span4">
          <img class="img-circle" data-src="holder.js/140x140" alt="140x140" style="width: 140px; height: 140px;" <%= image_tag "ico_mining.svg" %>
          <h2>Mining</h2>
          <p>You can start mining bitcoins to help processing transactions. In order to protect the network, you should join smaller mining pools and prefer decentralized pools like P2Pool or pools with getblocktemplate (GBT) support.</p>
        	 <% if signed_in? %>
        	 <%= link_to "View details", tutorial_path, :class => "btn" %>
       			<% else %>
        		 <%= link_to "View details", signin_path, :class => "btn" %>
        	 <% end %>
        </div>
         <div class="span4">
          <img class="img-circle" data-src="holder.js/140x140" alt="140x140" style="width: 140px; height: 140px;" <%= image_tag "ico_spread.svg" %>
          <h2>Spread</h2>
          <p>Speak about Bitcoin to interested people. Write about it on your blog. Tell your favorite shops you would like to pay with Bitcoin. Help keeping merchant directories up to date. Or be creative and make yourself a nice Bitcoin T-shirt.</p>
        	 <% if signed_in? %>
        	 <%= link_to "View details", tutorial_path, :class => "btn" %>
       			<% else %>
        		 <%= link_to "View details", signin_path, :class => "btn" %>
        	 <% end %>
        </div>
      </div><!-- /.row -->
    </div>

app/views/static_pages/tutorial.html.erb
<% provide(:title, 'Tutorial') %>
  <div class="body">
    <div id="content" class="content">
    <h1>Support Bitcoin</h1>
<p class="summarytxt">Bitcoin is a protocol that was born from a small community and has grown fast since. There are a lot of things you can do to help Bitcoin to spread and improve over time.</p>

    <ul class="media-list">
              <li class="media">
                <a class="pull-left" href="#">
                  <img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" <%= image_tag "ico_network.svg" %>
                </a>
                <div class="media-body">
                  <h4 class="media-heading">Be the network</h4>
     				<p>You can join the Bitcoin network by keeping <a href="/en/download">full node software</a> running on your computer or dedicated server. Full nodes are securing and relaying all users' transactions. They can be compared to the backbone of the network.</p>
                 </div>
              </li>
              <li class="media">
                <a class="pull-left" href="#">
                  <img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" <%= image_tag "ico_mining.svg" %>
                </a>
                <div class="media-body">
                	
                  <h4 class="media-heading">Mining</h4>
     			<p>You can start <a href="http://www.bitcoinmining.com/">mining bitcoins</a> to help processing transactions. In order to protect the network, you should join <a href="https://blockchain.info/pools">smaller mining pools</a> and prefer decentralized pools like <a href="http://p2pool.in/">P2Pool</a> or <a href="https://en.bitcoin.it/wiki/Comparison_of_mining_pools">pools</a> with getblocktemplate (GBT) support.</p>
                 </div>
             </li>
             <li class="media">
                <a class="pull-left" href="#">
                  <img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" <%= image_tag "ico_translate.svg" %>
             </a>
                <div class="media-body">
                  <h4 class="media-heading">Translate</h4>
     			<p>You can help to increase Bitcoin availability by translating or improving translations inside important parts of the Bitcoin ecosystem. Just pick a project you would like to help.</p>
                 </div>
              </li>
              <li class="media">
                <a class="pull-left" href="#">
                  <img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" <%= image_tag "ico_conf.svg" %>
                </a>
                <div class="media-body">
                  <h4 class="media-heading">Development</h4>
     				<p>Bitcoin is free software. So if you are a developer, you can use your super-powers to do good and <a href="/en/development">improve Bitcoin</a>. Or you can build amazing new services or software that can use Bitcoin.</p>
                 </div>
             </li>
             <li class="media">
                <a class="pull-left" href="#">
                  <img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" <%= image_tag "ico_donate.svg" %>
                </a>
                <div class="media-body">
                  <h4 class="media-heading">Donation</h4>
     				<p>The easiest way to help is to <a href="https://bitcoinfoundation.org/donate">donate</a> a few bitcoins to the Bitcoin Foundation. Or you can help directly fund any project related to Bitcoin that you believe will be helpful in the future.</p>
                 </div>
             </li>
             <li class="media">
                <a class="pull-left" href="#">
                  <img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" <%= image_tag "ico_law.svg" %>
                </a>
                <div class="media-body">
                  <h4 class="media-heading">Organizations</h4>
     				<p>The <a href="https://bitcoinfoundation.org/">Bitcoin Foundation</a> and many other <a href="/en/community#non-profit">non-profit organizations</a> are dedicated to protecting and promoting Bitcoin. You can help these groups by joining them and taking part in their projects, discussions and events.</p>
                 </div>
             </li>
              <li class="media">
                <a class="pull-left" href="#">
                  <img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" <%= image_tag "ico_spread.svg" %>
                </a>
                <div class="media-body">
                  <h4 class="media-heading">Spread</h4>
                  <p>Speak about Bitcoin to interested people. Write about it on your blog. Tell your favorite shops you would like to pay with Bitcoin. Help keeping <a href="http://usebitcoins.info/">merchant directories</a> up to date. Or be creative and make yourself a nice Bitcoin T-shirt.</p>
     				</div>
             </li>
              
              <li class="media">
                <a class="pull-left" href="#">
                  <img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" <%= image_tag "ico_wiki.svg" %>
                </a>
                <div class="media-body">
                  <h4 class="media-heading">Wiki</h4>
     				<p>The <a href="https://en.bitcoin.it/">Bitcoin wiki</a> is full of useful and detailed information and we are constantly improving the information it contains - just like Wikipedia. You can help keep the wiki accurate and up-to-date.</a>
                 </div>
             </li>
              <li class="media">
                <a class="pull-left" href="#">
                  <img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" <%= image_tag "ico_help.svg" %>
                </a>
                <div class="media-body">
                  <h4 class="media-heading">Meet the communities</h4>
     				<p>You can join Bitcoin <a href="/en/community">communities</a> and talk with other Bitcoin enthusiasts. You can learn more about Bitcoin every day, give help to new users and get involved in interesting projects.</p>
                 </div>
             </li>
            </ul>

app/views/static_pages/video.html.erb
<% provide(:title, 'Video') %>
    <h1>Videos</h1>
    <p>
      This is the video page Here is my email address
      <a href="mailto:email@darsedoyle@gmail.com?subject=Bitcoin Information">Darren Doyle</a>
      if you want to contact me
    </p>
     <legend>What is bitcoin?</legend>
    <div class="video-container">
         <iframe src="http://www.youtube.com/embed/Um63OQz3bjo" frameborder="0" width="560" height="315"></iframe>

</div>
 <legend>Bitcoin For Beginners - Learn How To Mine Bitcoin !</legend>
    <div class="video-container">
         <iframe src="http://www.youtube.com/embed/j7opj5-32hw" frameborder="0" width="560" height="315"></iframe>

</div>
 <legend>BitCoin for Beginners - Mac OS Mining, Tips, Mining Software, Wallets And More ! Part 2</legend>
    <div class="video-container">
         <iframe src="http://www.youtube.com/embed/ZEV3QFj19u8" frameborder="0" width="560" height="315"></iframe>

</div>
<legend>BitCoin For Beginners - POOLS - Top 3 Mining Pools - Trading and Exchanging - Part 3 1/2</legend>
    <div class="video-container">
         <iframe src="http://www.youtube.com/embed/pvrVtCOGTWY" frameborder="0" width="460" height="115"></iframe>
</div>

  

app/views/users/edit.html.erb
<% provide(:title, "Edit user")%>
<h1>Update your profile</h1>
<div class="row">
	<div class="span6 offset3">
		<%=form_for(@user) do |f|%>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.text_field :password %>

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<%end%>

		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails">change</a>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
</div> 
<legend>Here is the latest news on bitcoins from Twitter</legend>
<div class="tweet">
<p>
     	<a class="twitter-timeline" href="https://twitter.com/BitCoinReporter" data-widget-id="449192622590918657">Tweets by @BitCoinReporter</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </p>
    </div>